import React, { useEffect, useRef } from 'react';
import * as monaco from 'monaco-editor';
// Import Monaco CSS
import 'monaco-editor/min/vs/editor/editor.main.css';
import { configureMonacoYaml } from 'monaco-yaml';
import { Button, Undo, RotateRight, Code } from '@jahia/moonstone';
import { useTranslation } from 'react-i18next';

// Define workers for Monaco
// We need to explicitly point to the worker files generated by monaco-editor-webpack-plugin
// because we are running inside a Jahia module, not at the root.
window.MonacoEnvironment = {
    getWorker(workerId, label) {
        const basePath = (window.contextJsParameters?.contextPath || '') + '/modules/osgi-configurations-manager/javascript/apps/';
        if (label === 'yaml') {
            return new Worker(basePath + 'yaml.worker.js');
        }
        return new Worker(basePath + 'editor.worker.js');
    },
};

configureMonacoYaml(monaco, {
    enableSchemaRequest: true,
    hover: true,
    completion: true,
    validate: true,
    format: true,
});

export const YamlEditor = ({ value, onChange, onValidate }) => {
    const { t } = useTranslation('osgi-configurations-manager');
    const containerRef = useRef(null);
    const editorRef = useRef(null);

    useEffect(() => {
        if (containerRef.current) {
            editorRef.current = monaco.editor.create(containerRef.current, {
                value: value,
                language: 'yaml',
                theme: 'vs-light',
                minimap: { enabled: false },
                scrollBeyondLastLine: false,
                fontSize: 14,
                lineNumbers: 'on',
                glyphMargin: true,
                folding: true,
                automaticLayout: false // We use ResizeObserver
            });

            // Explicitly handle resizing
            const resizeObserver = new ResizeObserver(() => {
                if (editorRef.current) {
                    editorRef.current.layout();
                }
            });
            resizeObserver.observe(containerRef.current);

            // Change listener
            const subscription = editorRef.current.onDidChangeModelContent(() => {
                const newValue = editorRef.current.getValue();
                onChange(newValue);
            });

            // Validation listener
            const markerSubscription = monaco.editor.onDidChangeMarkers(() => {
                const model = editorRef.current.getModel();
                if (model) {
                    const markers = monaco.editor.getModelMarkers({ owner: 'yaml', resource: model.uri });
                    const hasErrors = markers.some(marker => marker.severity === monaco.MarkerSeverity.Error);
                    if (onValidate) {
                        onValidate(!hasErrors);
                    }
                }
            });

            return () => {
                subscription.dispose();
                markerSubscription.dispose();
                resizeObserver.disconnect();
                editorRef.current.dispose();
            };
        }
    }, []);

    // Update editor value if it changes from outside
    useEffect(() => {
        if (editorRef.current && editorRef.current.getValue() !== value) {
            editorRef.current.setValue(value);
        }
    }, [value]);

    const handleUndo = () => {
        editorRef.current?.trigger('toolbar', 'undo');
    };

    const handleRedo = () => {
        editorRef.current?.trigger('toolbar', 'redo');
    };

    const handleFormat = () => {
        editorRef.current?.getAction('editor.action.formatDocument').run();
    };

    return (
        <div style={{ flex: 1, minHeight: 0, minWidth: 0, width: '100%', display: 'flex', flexDirection: 'column' }}>
            <div style={{
                display: 'flex',
                gap: '8px',
                padding: '8px',
                borderBottom: '1px solid #ddd',
                backgroundColor: '#f9f9f9',
                alignItems: 'center'
            }}>
                <Button label={t('editor.button.undo')} variant="ghost" icon={<Undo />} onClick={handleUndo} title={t('tooltip.undo')} />
                <Button label={t('editor.button.redo')} variant="ghost" icon={<RotateRight />} onClick={handleRedo} title={t('tooltip.redo')} />
                <div style={{ width: '1px', background: '#ccc', margin: '0 4px', height: '20px' }} />
                <Button label={t('editor.button.format')} variant="ghost" icon={<Code />} onClick={handleFormat} title={t('tooltip.format')} />
            </div>

            <div style={{ flex: 1, position: 'relative' }}>
                <div
                    ref={containerRef}
                    style={{
                        position: 'absolute',
                        top: 0,
                        left: 0,
                        right: 0,
                        bottom: 0,
                        overflow: 'hidden'
                    }}
                />
            </div>
        </div>
    );
};
